// vue-chat/src/App.vue
<script setup lang="ts">
import { useSocket } from './composables/useSocket';
import ChatTitle from './components/ChatTitle.vue';
import ConnectionStatus from './components/ConnectionStatus.vue';
import UsernameForm from './components/UsernameForm.vue';
import ProfilePicturePicker from './components/ProfilePicturePicker.vue';
import MessageList from './components/MessageList.vue';
import MessageInput from './components/MessageInput.vue';

useSocket();
</script>

<template>
  <div class="app-container">
    <ChatTitle />
    <ConnectionStatus />
    <UsernameForm />
    <ProfilePicturePicker />
    <MessageList />
    <MessageInput />
  </div>
</template>

<style scoped>
  .app-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
  }
</style>

// react-chat/src/App.tsx
import { useSocket } from './hooks/useSocket';
import { ConnectionStatus } from './components/ConnectionStatus';
import { MessageList } from './components/MessageList';
import { MessageInput } from './components/MessageInput';
import { UsernameForm } from './components/UsernameForm';
import { ProfilePicturePicker } from './components/ProfilePicturePicker';

import './App.css';
import { Title } from './components/Title';

function App() {
  useSocket();

  return (
    <div className="app-container">
      <Title />
      <ConnectionStatus />
      <UsernameForm />
      <ProfilePicturePicker />
      <MessageList />
      <MessageInput />
    </div>
  );
}

export default App;
