// vue-chat/src/components/UsernameForm.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useChatStore } from '../stores/chatStore';

const chatStore = useChatStore();
const input = ref('');

function handleSubmit() {
  const trimmed = input.value.trim();
  if (!trimmed) return;
  chatStore.setUsername(trimmed);
  input.value = '';
}
</script>

<template>
  <div>
    <h2>Change Username</h2>
    <input
      v-model="input"
      type="text"
      placeholder="Username"
      @keydown.enter="handleSubmit"
    />
    <button :disabled="!input.trim()" @click="handleSubmit">Change</button>
  </div>
</template>

// react-chat/src/components/UsernameForm.tsx
import { useState } from 'react';
import { useChatStore } from '../store/useChatStore';
import './UsernameForm.css';

export function UsernameForm() {
  const setUsername = useChatStore((s) => s.setUsername);
  const [input, setInput] = useState('');

  const handleSubmit = () => {
    const trimmed = input.trim();
    if (!trimmed) return;
    setUsername(trimmed);
    setInput('');
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') handleSubmit();
  };

  return (
    <div className='input-container'>
      <h2>Change Username</h2>
      <input
        type="text"
        value={input}
        onChange={(e) => setInput(e.target.value)}
        onKeyDown={handleKeyDown}
        placeholder="Username"
      />
      <button onClick={handleSubmit} disabled={!input.trim()}>
        Change
      </button>
    </div>
  );
}
