// react-chat/src/components/MessageInput.tsx
import { useState } from 'react';
import { socket } from '../services/socket';
import { useChatStore } from '../store/useChatStore';

export function MessageInput() {
  const [text, setText] = useState('');
  const username = useChatStore((s) => s.username);
  const isConnected = useChatStore((s) => s.isConnected);
  const profilePictureIndex = useChatStore((s) => s.profilePictureIndex);

  const handleSend = () => {
    const trimmed = text.trim();
    const usernameToShow = username || 'unnamed';
    if (!trimmed || !isConnected) return;

    const message = {
      id: crypto.randomUUID(),
      text: trimmed,
      sender: usernameToShow,
      timestamp: Date.now(),
      profilePictureIndex,
    };

    socket.emit('message', message);
    setText('');
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') handleSend();
  };

  return (
    <div>
      <input
        type="text"
        value={text}
        onChange={(e) => setText(e.target.value)}
        onKeyDown={handleKeyDown}
        placeholder="Type a message..."
        disabled={!isConnected}
      />
      <button onClick={handleSend} disabled={!isConnected || !text.trim()}>
        Send
      </button>
    </div>
  );
}

// vue-chat/src/components/MessageInput.vue
<script setup lang="ts">
import { ref } from 'vue';
import { socket } from '../services/socket';
import { useChatStore } from '../stores/chatStore';

const chatStore = useChatStore();
const text = ref('');

function handleSend() {
  const trimmed = text.value.trim();
  const sender = chatStore.username || 'unnamed';
  if (!trimmed || !chatStore.isConnected) return;

  const message = {
    id: crypto.randomUUID(),
    text: trimmed,
    sender,
    timestamp: Date.now(),
    profilePictureIndex: chatStore.profilePictureIndex,
  };

  socket.emit('message', message);
  text.value = '';
}
</script>

<template>
  <div>
    <input
      v-model="text"
      type="text"
      placeholder="Type a message..."
      :disabled="!chatStore.isConnected"
      @keydown.enter="handleSend"
    />
    <button :disabled="!chatStore.isConnected || !text.trim()" @click="handleSend">
      Send
    </button>
  </div>
</template>
